### ISSUE TITLE
Does not compile with GCC11

### ISSUE THREAD

**Issue by gdonval** [conda-forge/lammps-feedstock#71]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The feedstock does not build (literally after git cloning). 

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
  active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.9.6.final.0
       virtual packages : __linux=2.6.32=0
                          __glibc=2.12=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /local/user/conda/pkgs
       envs directories : /opt/conda/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Linux/2.6.32-696.18.7.el6.x86_64 scientific/6.9 glibc/2.12
                UID:GID : 1263080:10306
             netrc file : None
           offline mode : False
```
</details>

Details about  <code>conda build</code> and system ( <code>conda build lammps-feedstock</code> ):
<details>

```
$ conda build lammps-feedstock
[...]
[ 82%] Building CXX object CMakeFiles/lammps.dir$SRC_DIR/src/USER-COLVARS/ndx_group.cpp.o
[ 82%] Building CXX object CMakeFiles/lammps.dir$SRC_DIR/src/USER-HDNNP/pair_hdnnp.cpp.o
/local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp: In member function 'virtual void LAMMPS_NS::PairHDNNP::compute(int, int)':
/local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp:83:27: error: no matching function for call to 'nnp::InterfaceLammps::setLocalAtoms(int&, int*&)'
   83 |   interface->setLocalAtoms(atom->nlocal,atom->type);
      |   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp:33:
/local/user/conda/lammps_1628689322053/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/InterfaceLammps.h:69:12: note: candidate: 'void nnp::InterfaceLammps::setLocalAtoms(int, const int*, const int*)'
   69 |     void   setLocalAtoms(int              numAtomsLocal,
      |            ^~~~~~~~~~~~~
/local/user/conda/lammps_1628689322053/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/InterfaceLammps.h:69:12: note:   candidate expects 3 arguments, 2 provided
/local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp:87:14: error: 'class nnp::InterfaceLammps' has no member named 'setLocalTags'; did you mean 'setLocalAtoms'?
   87 |   interface->setLocalTags(atom->tag);
      |              ^~~~~~~~~~~~
      |              setLocalAtoms
/local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp: In member function 'virtual void LAMMPS_NS::PairHDNNP::init_style()':
/local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp:262:35: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  262 |                         emap.c_str(),
      |                         ~~~~~~~~~~^~
      |                                   |
      |                                   const char*
In file included from /local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp:33:
/local/user/conda/lammps_1628689322053/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/InterfaceLammps.h:53:36: note:   initializing argument 2 of 'void nnp::InterfaceLammps::initialize(char* const&, char* const&, bool, bool, int, int, double, double, double, int, int)'
   53 |                       char* const& emap,
      |                       ~~~~~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/lammps.dir/build.make:9330: CMakeFiles/lammps.dir/local/user/conda/lammps_1628689322053/work/src/USER-HDNNP/pair_hdnnp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1113: CMakeFiles/lammps.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/apps/group/ce-molsim/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/local/user/conda/lammps_1628689322053/work/conda_build.sh']' returned non-zero exit status 2.
```
</details>

**Comment by gdonval** [comment]
When the "offending" package is disabled, I get a linking error:

<details>

```
$ conda build lammps-feedstock
[...]
[100%] Linking CXX executable lmp
/local/user/conda/lammps_1628693612439/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/11.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: /local/user/conda/lammps_1628693612439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libquip.a(IPModel_TS.o): undefined reference to symbol 'GOMP_loop_end@@GOMP_1.0'
/local/user/conda/lammps_1628693612439/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/11.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: /apps/group/ce-molsim/conda/lib/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lmp.dir/build.make:110: lmp] Error 1
make[1]: *** [CMakeFiles/Makefile2:916: CMakeFiles/lmp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/apps/group/ce-molsim/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/apps/group/ce-molsim/conda/lib/python3.9/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/local/user/conda/lammps_1628693612439/work/conda_build.sh']' returned non-zero exit status 2.
```

</details>

**Comment by jan-janssen** [comment]
You can try to disable `quip` as well: 
```
libquip.a(IPModel_TS.o): undefined reference to symbol 'GOMP_loop_end@@GOMP_1.0'
```

**Comment by jakirkham** [comment]
Is this still relevant?

**Comment by jan-janssen** [comment]
No, so I am going to close this issue.
